[project]
name = "stratum-moe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets>=4.5.0",
    "psycopg[binary]>=3.3.2",
    "sentence-transformers>=5.2.0",
    "transformers>=4.57.6",
]
